POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Doro",
    "password": "123456"
}


### 
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "Doro",
    "password": "123456"
}

###
POST http://localhost:5000/api/posts
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmIzZGZiMjFmOTljYzI3MzhlOGIxZmQiLCJpYXQiOjE2NTU5NTUzNzh9.3KNswnrtiWDRX4x8-IJ2v2cgqIYTJ3ZX79vNowYOg1Q

{
    "title": "ReactJS",
    "description": "ReactJS",
    "url": "ReactJS.org",
    "status": "Learning"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmIzZGZiMjFmOTljYzI3MzhlOGIxZmQiLCJpYXQiOjE2NTU5NTUzNzh9.3KNswnrtiWDRX4x8-IJ2v2cgqIYTJ3ZX79vNowYOg1Q

###
PUT http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmIzZGZiMjFmOTljYzI3MzhlOGIxZmQiLCJpYXQiOjE2NTU5NTUzNzh9.3KNswnrtiWDRX4x8-IJ2v2cgqIYTJ3ZX79vNowYOg1Q
